### ISSUE TITLE
先输入AFK验证再登陆会导致无法操作等2个bug

### ISSUE THREAD

**Issue by Zhou-Shilin** [MakesYT/NchargeAntiAFK#1]
1. 如果先输入AFK验证再登陆，会显示验证成功，但实则不能放置/摧毁方块或与方块交互。
但如果进入游戏后先登录，再输入AFK验证则正常。
2. 玩家死亡后，过久不点击重生，那么重生后会莫名其妙要求AFK验证，并且没有任何提示(要求输入n+n=?这种)

**Comment by Maklith** [comment]
版本1.2.1中
1问题我已经尝试修复,但无法复现,请进行尝试
2问题已经添加玩家复活后的再次提醒
如没有其它问题,请关闭issue
