### ISSUE TITLE
功能提议

### ISSUE THREAD

**Issue by Zhou-Shilin** [MakesYT/NchargeAntiAFK#2]
把配置blockquote command的配置新增modify-view-distance选项
`<blockquote>command: "modify-view-distance" #让玩家执行的命令(无需/) 用占位符%p表示玩家名字 null即使用AFK踢出, modify-view-distance即更改玩家视野为2, 一定要有""
`
作用：判定为AFK则强制修改其视野为2

**Comment by Maklith** [comment]
仅凭bukkit的情况下我不知道这种效果该如何实现，如果有实现了此功能的插件可以发送给我，以供参考

**Comment by Zhou-Shilin** [comment]
> 仅凭bukkit的情况下我不知道这种效果该如何实现，如果有实现了此功能的插件可以发送给我，以供参考

参考：https://www.spigotmc.org/resources/view-distance-tweaks-1-14-1-19.75164/
其可以根据服务器卡顿情况对所有玩家的视野进行调整，但我不清楚是否可以做到对单个玩家的视野调整

**Comment by Zhou-Shilin** [comment]
> 仅凭bukkit的情况下我不知道这种效果该如何实现，如果有实现了此功能的插件可以发送给我，以供参考

参考：https://www.spigotmc.org/resources/set-my-view-distance.59822/   可以对单个玩家的视野进行调整

**Comment by Zhou-Shilin** [comment]
> 仅凭bukkit的情况下我不知道这种效果该如何实现，如果有实现了此功能的插件可以发送给我，以供参考

我浏览了一下那个插件的代码，似乎可以通过`player.setViewDistance(int)`实现
（本人没有java基础，不懂）
其完整代码如下：

```
package com.cgsama.mc;

import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.permissions.Permission;
import org.bukkit.permissions.PermissionDefault;
import org.bukkit.plugin.java.JavaPlugin;

public class SetMyViewDistance extends JavaPlugin implements Listener {

   public void onEnable() {
      this.getServer().getPluginManager().registerEvents(this, this);
   }
   
   // 我的批注：这里似乎是指令的监听器
   public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
      Player player = (Player)sender;
      if(cmd.getName().equals("smvd") && sender.hasPermission("smvd.set")) {
         boolean d = false;

         try {
            int d1 = Integer.parseInt(args[0]);
            //  我的批注：检测数值是否合法？
            if(d1 > 64 || d1 < 1) {
               player.sendMessage("View distance should be an int in range (0, 64]");
               return true;
            }

            player.sendMessage("Your view distance has been set to " + d1);
            this.getLogger().info("Set view distance to " + d1 + " for player " + player.getName());
            player.setViewDistance(d1);
            // 我的批注：上面那行应该是修改玩家视野的代码
         } catch (Exception var8) {
            //  我的批注：若指令不合法则提示玩家语法？
            player.sendMessage("Please use the format /smvd [int]");
         }
      } else {
         //  我的批注：没权限的提示？
         player.sendMessage("Permission rejected");
      }

      return true;
   }

   @EventHandler
   public void onPlayerJoin(PlayerJoinEvent e) {
      //  我的批注：玩家上线后检测玩家权限？
      Player p = e.getPlayer();
      int d = 1;
      if(p.hasPermission(new Permission("smvd.tiny", PermissionDefault.FALSE))) {
         d = 4;
      }

      if(p.hasPermission(new Permission("smvd.near", PermissionDefault.FALSE))) {
         d = 6;
      }

      if(p.hasPermission(new Permission("smvd.normal", PermissionDefault.FALSE))) {
         d = 9;
      }

      if(p.hasPermission(new Permission("smvd.far", PermissionDefault.FALSE))) {
         d = 12;
      }

      if(p.hasPermission(new Permission("smvd.extreme", PermissionDefault.FALSE))) {
         d = 15;
      }

      for(int i = 1; i < 65; ++i) {
         if(p.hasPermission(new Permission("smvd.value." + i, PermissionDefault.FALSE))) {
            d = i;
         }
      }

      d = this.getServer().getViewDistance() > d?this.getServer().getViewDistance():d;
      p.sendMessage("Your view distance has been set to " + d);
      this.getLogger().info("Set view distance to " + d + " for player " + p.getName());
      p.setViewDistance(d);
   }
}
```

**Comment by Maklith** [comment]
> > 仅凭bukkit的情况下我不知道这种效果该如何实现，如果有实现了此功能的插件可以发送给我，以供参考
> 
> 我浏览了一下那个插件的代码，似乎可以通过`player.setViewDistance(int)`实现
> （本人没有java基础，不懂）
> 其完整代码如下：
> 
> ```
> package com.cgsama.mc;
> 
> import org.bukkit.command.Command;
> import org.bukkit.command.CommandSender;
> import org.bukkit.entity.Player;
> import org.bukkit.event.EventHandler;
> import org.bukkit.event.Listener;
> import org.bukkit.event.player.PlayerJoinEvent;
> import org.bukkit.permissions.Permission;
> import org.bukkit.permissions.PermissionDefault;
> import org.bukkit.plugin.java.JavaPlugin;
> 
> public class SetMyViewDistance extends JavaPlugin implements Listener {
> 
>    public void onEnable() {
>       this.getServer().getPluginManager().registerEvents(this, this);
>    }
>    
>    // 我的批注：这里似乎是指令的监听器
>    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
>       Player player = (Player)sender;
>       if(cmd.getName().equals("smvd") && sender.hasPermission("smvd.set")) {
>          boolean d = false;
> 
>          try {
>             int d1 = Integer.parseInt(args[0]);
>             //  我的批注：检测数值是否合法？
>             if(d1 > 64 || d1 < 1) {
>                player.sendMessage("View distance should be an int in range (0, 64]");
>                return true;
>             }
> 
>             player.sendMessage("Your view distance has been set to " + d1);
>             this.getLogger().info("Set view distance to " + d1 + " for player " + player.getName());
>             player.setViewDistance(d1);
>             // 我的批注：上面那行应该是修改玩家视野的代码
>          } catch (Exception var8) {
>             //  我的批注：若指令不合法则提示玩家语法？
>             player.sendMessage("Please use the format /smvd [int]");
>          }
>       } else {
>          //  我的批注：没权限的提示？
>          player.sendMessage("Permission rejected");
>       }
> 
>       return true;
>    }
> 
>    @EventHandler
>    public void onPlayerJoin(PlayerJoinEvent e) {
>       //  我的批注：玩家上线后检测玩家权限？
>       Player p = e.getPlayer();
>       int d = 1;
>       if(p.hasPermission(new Permission("smvd.tiny", PermissionDefault.FALSE))) {
>          d = 4;
>       }
> 
>       if(p.hasPermission(new Permission("smvd.near", PermissionDefault.FALSE))) {
>          d = 6;
>       }
> 
>       if(p.hasPermission(new Permission("smvd.normal", PermissionDefault.FALSE))) {
>          d = 9;
>       }
> 
>       if(p.hasPermission(new Permission("smvd.far", PermissionDefault.FALSE))) {
>          d = 12;
>       }
> 
>       if(p.hasPermission(new Permission("smvd.extreme", PermissionDefault.FALSE))) {
>          d = 15;
>       }
> 
>       for(int i = 1; i < 65; ++i) {
>          if(p.hasPermission(new Permission("smvd.value." + i, PermissionDefault.FALSE))) {
>             d = i;
>          }
>       }
> 
>       d = this.getServer().getViewDistance() > d?this.getServer().getViewDistance():d;
>       p.sendMessage("Your view distance has been set to " + d);
>       this.getLogger().info("Set view distance to " + d + " for player " + p.getName());
>       p.setViewDistance(d);
>    }
> }
> ```

官方没有提示有这个方法，我会尝试，但不保证可用，也许已经在某个版本中移除

**Comment by Zhou-Shilin** [comment]
> > > 仅凭bukkit的情况下我不知道这种效果该如何实现，如果有实现了此功能的插件可以发送给我，以供参考
> > 
> > 
> > 我浏览了一下那个插件的代码，似乎可以通过`player.setViewDistance(int)`实现
> > （本人没有java基础，不懂）
> > 其完整代码如下：
> > ```
> > package com.cgsama.mc;
> > 
> > import org.bukkit.command.Command;
> > import org.bukkit.command.CommandSender;
> > import org.bukkit.entity.Player;
> > import org.bukkit.event.EventHandler;
> > import org.bukkit.event.Listener;
> > import org.bukkit.event.player.PlayerJoinEvent;
> > import org.bukkit.permissions.Permission;
> > import org.bukkit.permissions.PermissionDefault;
> > import org.bukkit.plugin.java.JavaPlugin;
> > 
> > public class SetMyViewDistance extends JavaPlugin implements Listener {
> > 
> >    public void onEnable() {
> >       this.getServer().getPluginManager().registerEvents(this, this);
> >    }
> >    
> >    // 我的批注：这里似乎是指令的监听器
> >    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
> >       Player player = (Player)sender;
> >       if(cmd.getName().equals("smvd") && sender.hasPermission("smvd.set")) {
> >          boolean d = false;
> > 
> >          try {
> >             int d1 = Integer.parseInt(args[0]);
> >             //  我的批注：检测数值是否合法？
> >             if(d1 > 64 || d1 < 1) {
> >                player.sendMessage("View distance should be an int in range (0, 64]");
> >                return true;
> >             }
> > 
> >             player.sendMessage("Your view distance has been set to " + d1);
> >             this.getLogger().info("Set view distance to " + d1 + " for player " + player.getName());
> >             player.setViewDistance(d1);
> >             // 我的批注：上面那行应该是修改玩家视野的代码
> >          } catch (Exception var8) {
> >             //  我的批注：若指令不合法则提示玩家语法？
> >             player.sendMessage("Please use the format /smvd [int]");
> >          }
> >       } else {
> >          //  我的批注：没权限的提示？
> >          player.sendMessage("Permission rejected");
> >       }
> > 
> >       return true;
> >    }
> > 
> >    @EventHandler
> >    public void onPlayerJoin(PlayerJoinEvent e) {
> >       //  我的批注：玩家上线后检测玩家权限？
> >       Player p = e.getPlayer();
> >       int d = 1;
> >       if(p.hasPermission(new Permission("smvd.tiny", PermissionDefault.FALSE))) {
> >          d = 4;
> >       }
> > 
> >       if(p.hasPermission(new Permission("smvd.near", PermissionDefault.FALSE))) {
> >          d = 6;
> >       }
> > 
> >       if(p.hasPermission(new Permission("smvd.normal", PermissionDefault.FALSE))) {
> >          d = 9;
> >       }
> > 
> >       if(p.hasPermission(new Permission("smvd.far", PermissionDefault.FALSE))) {
> >          d = 12;
> >       }
> > 
> >       if(p.hasPermission(new Permission("smvd.extreme", PermissionDefault.FALSE))) {
> >          d = 15;
> >       }
> > 
> >       for(int i = 1; i < 65; ++i) {
> >          if(p.hasPermission(new Permission("smvd.value." + i, PermissionDefault.FALSE))) {
> >             d = i;
> >          }
> >       }
> > 
> >       d = this.getServer().getViewDistance() > d?this.getServer().getViewDistance():d;
> >       p.sendMessage("Your view distance has been set to " + d);
> >       this.getLogger().info("Set view distance to " + d + " for player " + p.getName());
> >       p.setViewDistance(d);
> >    }
> > }
> > ```
> 
> 官方没有提示有这个方法，我会尝试，但不保证可用，也许已经在某个版本中移除

好！

**Comment by Maklith** [comment]
确认为paper API，不会考虑单独版本
